version: 5.1.0
variant: default
logo: /img/logo.png
head:
    favicon: /img/favicon.png
    manifest:
        name: 浮枕星海
        short_name: 浮枕
        start_url: https://universesaurora.top/
        theme_color: '#9932CC'
        background_color: '#9932CC'
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        友链: /links
        关于: /about
    links: 
footer:
    copyright: 世界は、あなたのスキで目覚め、変わってゆくものなのですから...
    links:
        CC BY-NC-SA 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/
        CC BY-NC-SA 4.0 icons:
            icon:
                - fab fa-creative-commons
                - fab fa-creative-commons-by
                - fab fa-creative-commons-nc
                - fab fa-creative-commons-sa
            url: https://creativecommons.org/licenses/by-nc-sa/4.0/
article:
    highlight:
        theme: xcode
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: auto
    updated_auto_hide: true
    licenses:
        CC BY-NC-SA 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/licenses/by-nc-sa/4.0/
        CC BY:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by-nc-sa/4.0/
        CC NC:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc-sa/4.0/
        CC SA:
            icon: fab fa-creative-commons-sa
            url: https://creativecommons.org/licenses/by-nc-sa/4.0/
search:
    type: insight
comment:
    type: gitalk
    client_id: 0d93b8fa7142b6c21de0
    client_secret: fd1449c0798a980110bd15b1a5e35ea3d590d9aa
    repo: universesaurora-blog
    owner: UniversesAurora
    admin:
        - UniversesAurora
    per_page: 20
    enable_hotkey: true
    language: zh-CN
share:
    type: sharethis
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=6291b3ba6ad7c40019490138&product=sop
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: 浮枕
        author_title: Kernel panic at 0xffff467573696f6e
        location: 中央図書館断絶の壁分室
        avatar: /img/avatar.png
        avatar_rounded: true
        gravatar: 
        follow_link: https://twitter.com/universesaurora
        social_links:
            Telegram:
                icon: fab fa-telegram
                url: https://t.me/universesaurora
            Mastodon:
                icon: fab fa-mastodon
                url: https://mastodon.social/@universesaurora
            Bluesky:
                icon: fab fa-twitter
                url: https://bsky.app/profile/universesaurora.bsky.social
            Github:
                icon: fab fa-github
                url: https://github.com/UniversesAurora
            Email:
                icon: fas fa-envelope
                url: mailto:universesaurora@gmail.com
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        position: right
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: recent_posts
    -
        position: left
        type: tags
    -
        position: left
        type: followit
        description: 
        action_url: https://api.follow.it/subscription-form/a1BGa2tQbURTbStQandqbGNOeWgzcytQME9iVityYVNVaVVGR2N5NzlGZDFaWDlHYnRLc0hmczZrVDFOY3dzamVYTDFIdGZxOVgvNTJwRm5RNjlqVVN5RzBNK0M1RVBUOEhlZXUwOEtyWG8vRVhPRUR4RFZFeUdwbTArSE0vdmF8dkswd0lGYUxxRGM0RHpnd280RDBtT3JXenNZQ2N6RG5oeVNjMjVTNitlcz0=/8
        verification_code: 6w6wNNa9dLg34hkzxXZS
    -
        position: left
        type: links
        links:
            Moeka: https://MoeClue.com/
            小莫のBase: https://mou.best
    -
        position: right
        type: categories
    -
        position: right
        type: archives
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: true
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-right
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: UA-172917863-2
    hotjar:
        site_id: 
    katex: false
    mathjax: true
    outdated_browser: true
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: '[cdnjs]https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-d/${package}/${version}/${filename}'
    fontcdn: 'https://google-fonts.mirrors.sjtug.sjtu.edu.cn/${type}?family=${fontname}'
    iconcdn: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-d/font-awesome/5.15.4/css/all.min.css'
