name: Pages

on:
  push:
    branches:
      - src  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Customize theme
        run: |
          rm -rf node_modules/hexo-theme-icarus/source/img
          sed -i "0,/default: fontcdn(.*)/{s//default: fontcdn('Source+Serif+Pro\\&family=Roboto+Mono\\&family=Noto+Serif+SC', 'css2')/}" node_modules/hexo-theme-icarus/layout/common/head.jsx
          sed -i "0,/\\\$family-sans-serif ?= Ubuntu, Roboto, 'Open Sans', 'Microsoft YaHei', sans-serif/{s//\\\$family-sans-serif ?= 'Source Serif Pro', 'Source Han Serif SC', 'Noto Serif CJK SC', 'Noto Serif SC', serif/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\\\$family-code ?= 'Source Code Pro', monospace, 'Microsoft YaHei'/{s//\\\$family-code ?= 'Roboto Mono', monospace, 'Source Serif Pro', 'Source Han Serif SC', 'Noto Serif CJK SC', 'Noto Serif SC', serif/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\\\$primary ?= \\\$blue/{s//\\\$primary ?= \\\$purple/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\\\$menu-item-active-color ?= \\\$link/{s//\\\$menu-item-active-color ?= \\\$purple/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/{link\.icon ? <i class={link\.icon}><\/i> : name}/{s//{link\.icon ? (Array\.isArray(link\.icon) ? link\.icon\.map(i => \[<i className={i}><\/i>, '\\\\u00A0'\]) : <i className={link\.icon}><\/i>) : name}/}" node_modules/hexo-theme-icarus/layout/common/footer.jsx
          sed -i "0,/\"\\\$ref\": \"\/misc\/poly_links\.json\",/{s///}" node_modules/hexo-theme-icarus/include/schema/common/footer.json
          sed -i -z "0,/\.widget\n    \.menu-list\n        li\n            ul\n                margin-right: 0/{s//\.widget\n    \.menu-list\n        li\n            ul\n                margin-right: 0\n        a\n            transition: background-color 0\.3s ease-in-out/}" node_modules/hexo-theme-icarus/include/style/widget.styl
          sed -i "0,/border-radius: \\\$card-radius/{s//border-radius: \\\$card-radius\n    \\&:hover\n        box-shadow: 0 6px 15px rgba(0,0,0,0\.15), 0 0 1px rgba(0,0,0,0\.1)/}" node_modules/hexo-theme-icarus/include/style/card.styl
          sed -i "s/element\.style\.transition = 'opacity 0\.3s ease-out, transform 0\.3s ease-out';/element\.style\.transition = 'opacity 0\.3s ease-out, transform 0\.3s ease-out, box-shadow 0\.3s ease-in-out';/g" node_modules/hexo-theme-icarus/source/js/animation.js
          sed -i "0,/\\\$tablet ?=.*/{s//\\\$tablet ?= 1100px/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\\\$desktop ?=.*/{s//\\\$desktop ?= 1400px/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\\\$widescreen ?=.*/{s//\\\$widescreen ?= 1600px/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\\\$fullhd ?=.*/{s//\\\$fullhd ?= 1920px/}" node_modules/hexo-theme-icarus/include/style/base.styl
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG_TOKEN }}
          publish_dir: ./public
          publish_branch: page