name: Pages

on:
  push:
    branches:
      - src  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Customize theme
        run: |
          sed -i "0,/default: fontcdn(.*)/{s//default: fontcdn('Source+Serif+Pro\\&family=Roboto+Mono\\&family=Noto+Serif+SC', 'css2')/}" node_modules/hexo-theme-icarus/layout/common/head.jsx
          sed -i "0,/\$family-sans-serif ?= Ubuntu, Roboto, 'Open Sans', 'Microsoft YaHei', sans-serif/{s//\$family-sans-serif ?= 'Source Serif Pro', 'Source Han Serif SC', 'Noto Serif CJK SC', 'Noto Serif SC', serif/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\$family-code ?= 'Source Code Pro', monospace, 'Microsoft YaHei'/{s//\$family-code ?= 'Roboto Mono', monospace, 'Source Serif Pro', 'Source Han Serif SC', 'Noto Serif CJK SC', 'Noto Serif SC', serif/}" node_modules/hexo-theme-icarus/include/style/base.styl
          sed -i "0,/\$primary ?= \$blue/{s//\$primary ?= \$purple/}" node_modules/hexo-theme-icarus/include/style/base.styl
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG_TOKEN }}
          publish_dir: ./public
          publish_branch: page